# cart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  replicas: {{ .Values.app.cart.replicaCount }}
  template: 
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-container
        image: {{ .Values.image.repository }}/cart-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: service-url
        - configMapRef:
            name: app-db-setting
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name:  cart-service
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: default
spec:
  maxReplicas: {{ .Values.hpa.cart.maxReplicas }}
  minReplicas: {{ .Values.hpa.cart.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # intentionally using a small value. default: 300
  metrics:
    - type: Object
      object:
        metric:
          name: request_duration_seconds_90ile
        describedObject:
          apiVersion: apps/v1
          kind: Deployment
          name: cart
        target:
          type: Value
          value: {{ .Values.hpa.cart.targetValue }}
